services:
  peg.api.mutation.peg:
    class: Peg\Bundles\ApiBundle\GraphQL\Mutation\PegMutation
    arguments:
      - "@tactician.commandbus"
      - "@peg.util.short_code_generator"
    tags:
      - { name: overblog_graphql.mutation, alias: "peg_mutation_create", method: "createPeg" }

  peg.api.mutation.peg_location_event:
    class: Peg\Bundles\ApiBundle\GraphQL\Mutation\PegEventMutation
    arguments:
      - "@tactician.commandbus"
    tags:
      - { name: overblog_graphql.mutation, alias: "peg_comment_event_mutation_create", method: "createPegCommentEvent" }
      - { name: overblog_graphql.mutation, alias: "peg_picture_event_mutation_create", method: "createPegPictureEvent" }
