services:
  peg.persistence.command.peg_create.handler:
    class: Peg\Domain\Commands\PegCreateHandler
    arguments:
      - "@doctrine.odm.mongodb.document_manager"
    tags:
      - { name: tactician.handler, command: Peg\Domain\Commands\PegCreate }

  peg.persistence.command.add_comment.handler:
    class: Peg\Domain\Commands\AddPegEventHandler
    arguments:
      - "@peg.api_bundle.repository.doctrine.odm.peg"
      - "@peg.api_bundle.repository.doctrine.odm.peg_event"
    tags:
      - { name: tactician.handler, command: Peg\Domain\Commands\AddPegEvent }
