Peg:
  type: object
  config:
    description: "You know… a clothes peg!"
    fields:
      id:
        type: "String!"
        description: "The ID of the peg"
      shortcode:
        type: "String"
        description: "Shortcode used to access the peg"
      pegEvents:
        type: "[PegEvent]"
        description: "Ohhh.. what happened to me?!"
        resolve: "@=resolver('peg_events', [value, args])"
        args:
          type:
            type: "PegEventType"
          order:
            type: "QueryOrder"
            description: "Default is ASC"
      createPegCommentEvent:
        type: "PegEvent"
        args:
          comment:
            type: "String!"
          location:
            type: "String"
          email:
            type: "String"
        resolve: "@=mutation('peg_comment_event_mutation_create', [value, args['comment'], args['location'], args['email']])"
      createPegPictureEvent:
        type: "PegEvent"
        args:
          pictureUrl:
            type: "String!"
            description: "You know… where the image is"
          comment:
            type: "String"
          location:
            type: "String"
          email:
            type: "String"
        resolve: "@=mutation('peg_picture_event_mutation_create', [value, args['pictureUrl'], args['comment'], args['location'], args['email']])"
